name: 🔬 Artifact Producer Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create artifact dynamically
        run: |
          echo "This is an artifact for run ID: ${{ github.run_id }}" > dynamic-artifact-${{ github.run_id }}.txt

      - name: Upload artifact with dynamic name
        uses: actions/upload-artifact@v4
        with:
          name: dynamic-artifact-${{ github.run_id }}
          path: dynamic-artifact-${{ github.run_id }}.txt


