name: 🔬 Artifact Producer

on:
  workflow_dispatch:

jobs:
  produce_artifact:
    name: Upload Dynamically Named Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate artifact file
        run: |
          echo "This is the artifact from run ID: ${{ github.run_id }}" > artifact.txt

      - name: Upload artifact
        # id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: dynamic-artifact-${{ github.run_id }}
          path: artifact.txt

      - name: Set run_id output
        id: set_output
        run: echo "run_id=${{ github.run_id }}" >> $GITHUB_ENV

    outputs:
      run_id: ${{ steps.set_output.outputs.run_id }}
