name: 🔬 Artifact Producer Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a dynamic artifact name
        run: echo "dynamic-artifact-${{ github.run_id }}.txt" > artifact_name.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dynamic-artifact-${{ github.run_id }}
          path: artifact_name.txt

      - name: Set output artifact name
        id: set_output
        run: echo "artifact_name=dynamic-artifact-${{ github.run_id }}.txt" >> $GITHUB_ENV
