name: Test Signed and Verified Commits

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: "Version to bump to"
        required: true

jobs:
  bump_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for pushing commits
    steps:
      - uses: actions/checkout@v4
        # with:
        # fetch-depth: 0 # not required for committing new changes (only for full history / tags)

      #      - name: Setup Node
      #        uses: actions/setup-node@v4
      #        with:
      #          node-version: 20

      #      - name: Install deps
      #        run: npm ci

      - name: Run bump+commit per repo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT || github.token }}
          RTP_VERSION: ${{ inputs.rtp_version }}
        run: node ./.build/github/actions/rtp-bump.js