name: Test CloudFront Update Simulation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment: dev, acc, prev or prod'
        type: environment
        required: true

jobs:
  simulate-cloudfront-update:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Simulate CloudFront distribution updates
        run: |
          echo "Starting simulation..."
          
          # Access environment variables
          distribution_ids=${{ vars.CLOUDFRONT_DISTRIB_IDS }}
          origin_names=${{ vars.CLOUDFRONT_DISTRIB_ORIGIN_NAMES }}

          echo "Distribution IDs: $distribution_ids"
          echo "Origin Names: $origin_names"

          # Convert strings to arrays
          IFS=',' read -r -a distribution_id_array <<< "$distribution_ids"
          IFS=',' read -r -a origin_names_array <<< "$origin_names"

          # Simulate processing each distribution
          for distribution_id in "${distribution_id_array[@]}"; do
            echo "Processing distribution ID: $distribution_id"
            
            # Mock the distribution config (simulating the AWS response)
            distribution_config=$(cat distribution-config.json)

            # Process each origin
            for origin_name in "${origin_names_array[@]}"; do
              echo "Processing origin name: $origin_name for distribution $distribution_id"
              
              # Update the OriginReadTimeout and OriginKeepaliveTimeout for each origin using jq
              updated_config=$(echo "$distribution_config" | jq \
                --arg origin_name "$origin_name" \
                '(.DistributionConfig.Origins.Items[] 
                  | select(.DomainName == $origin_name) 
                  | .CustomOriginConfig.OriginReadTimeout = 60 
                  | .CustomOriginConfig.OriginKeepaliveTimeout = 30)')

              # Save the updated config to a new file
              echo "$updated_config" > updated-distribution-config.json

              # Extract the updated ETag (mocked)
              # ETag=$(echo "$updated_config" | jq -r '.ETag')
              ETag=$(jq -r '.ETag' distribution-config.json)

              echo "Updated ETag: $ETag"
              
              # Print the updated config (simulating what would be sent to AWS)
              echo "Updated JSON for origin $origin_name in distribution $distribution_id"
              echo "$updated_config" | jq .
            done
          done
