name: Test CloudFront Update Simulation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment: dev, acc, prev or prod'
        type: environment
        required: true

jobs:
  simulate-cloudfront-update:
    runs-on: ubuntu-latest

    steps:
      - name: Simulate CloudFront distribution updates
        env:  # Use env to pass variables from GitHub vars/secrets
          CLOUDFRONT_DISTRIB_IDS: ${{ vars.CLOUDFRONT_DISTRIB_IDS }}
          CLOUDFRONT_DISTRIB_ORIGIN_NAMES: ${{ vars.CLOUDFRONT_DISTRIB_ORIGIN_NAMES }}
        run: |
          echo "Starting simulation..."
          
          # Access environment variables
          distribution_ids="$CLOUDFRONT_DISTRIB_IDS"
          origin_names="$CLOUDFRONT_DISTRIB_ORIGIN_NAMES"

          echo "Distribution IDs: $distribution_ids"
          echo "Origin Names: $origin_names"

          # Convert strings to arrays
          IFS=',' read -r -a distribution_id_array <<< "$distribution_ids"
          IFS=',' read -r -a origin_names_array <<< "$origin_names"

          for distribution_id in "${distribution_id_array[@]}"; do
            echo "Processing distribution ID: $distribution_id"
            
            for origin_name in "${origin_names_array[@]}"; do
              echo "Processing origin name: $origin_name for distribution $distribution_id"
            done
          done
